### ISSUE TITLE
Fails to build with musl 1.2.5

### ISSUE THREAD

**Issue by alyssais** [talex5/ocaml-wayland#45]
musl 1.2.5 newly provides some statx support in <sys/stat.h>, but it does not define the `STATX_ATTR_*` constants, causing this build failure:

```
run: gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC  -D_GNU_SOURCE -I /build/uring-0.8/_build/default/lib/uring/include -I /nix/store/yspc3sc7nkgspq2l0larmf46flhk1r4n-ocaml-5.0.0/lib/ocaml -o /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.o -c /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c -lm -lpthread
-> process exited with code 1
-> stdout:
-> stderr:
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:198:14: error: ‘STATX_ATTR_COMPRESSED’ undeclared here (not in a function)
 |   198 |   DUNE_SIGN((STATX_ATTR_COMPRESSED)),
 |       |              ^~~~~~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:206:14: error: ‘STATX_ATTR_IMMUTABLE’ undeclared here (not in a function)
 |   206 |   DUNE_SIGN((STATX_ATTR_IMMUTABLE)),
 |       |              ^~~~~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:214:14: error: ‘STATX_ATTR_APPEND’ undeclared here (not in a function)
 |   214 |   DUNE_SIGN((STATX_ATTR_APPEND)),
 |       |              ^~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:222:14: error: ‘STATX_ATTR_NODUMP’ undeclared here (not in a function); did you mean ‘STATX_ATTR_DAX’?
 |   222 |   DUNE_SIGN((STATX_ATTR_NODUMP)),
 |       |              ^~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:230:14: error: ‘STATX_ATTR_ENCRYPTED’ undeclared here (not in a function); did you mean ‘STATX_ATTR_VERITY’?
 |   230 |   DUNE_SIGN((STATX_ATTR_ENCRYPTED)),
 |       |              ^~~~~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
Error: failed to compile program
```

It's not possible to just include <linux/stat.h> afterwards, if some constants are missing from <sys/stat.h>, because then there will be type redefinition errors for e.g. `struct statx`.

**Comment by alyssais** [comment]
Ahh, wrong repo — how did I do that?  Sorry.
